version: '2'
services:
  feedback:
    build:
      context: .
    volumes:
      - .:/app
    env_file:
      .env
    expose:
      - "5000"
    ports:
      - "80:5000"
  api:
    build:
      context: ./api
    volumes:
      - ./api:/api
    env_file: .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
